StylesPath = styles
MinAlertLevel = suggestion

Packages = https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip, \
  https://github.com/tbhb/vale-ai-tells/releases/download/v1.31.0/ai-tells.zip, \
  https://github.com/tbhb/vale-ai-tells/releases/download/v1.31.0/ai-tells-commits.zip

[*.md]
BasedOnStyles = write-good, ai-tells
;write-good.E-Prime = NO
;write-good.TooWordy = NO
;write-good.So = NO
ai-tells.EmDashUsage = NO

[formats]
gitcommit = md

[*.gitcommit]
BasedOnStyles = ai-tells-commits
ai-tells-commits.CommitAttribution = NO
